# Generated by Django 2.1.5 on 2019-04-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0002_auto_20190222_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chart', models.IntegerField(unique=True)),
                ('xAxis_Name', models.CharField(max_length=264)),
                ('yAxis_Name', models.CharField(max_length=264)),
                ('title', models.CharField(max_length=264)),
                ('interval', models.IntegerField()),
                ('comandline', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('parameter', models.FloatField()),
                ('id_chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnumonitor.Chart')),
            ],
        ),
        migrations.DeleteModel(
            name='MonitorData',
        ),
    ]
