# Generated by Django 2.1.5 on 2019-04-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0003_auto_20190404_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_chart',
            old_name='parameter',
            new_name='value',
        ),
    ]
