# Generated by Django 2.1.5 on 2019-04-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0004_auto_20190404_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='id_chart',
        ),
    ]
