# Generated by Django 2.1.5 on 2019-04-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0007_remove_chart_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='commandline',
            new_name='parameter',
        ),
    ]
