# Generated by Django 2.1.5 on 2019-04-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0008_auto_20190412_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('error', models.CharField(max_length=264)),
                ('type', models.CharField(max_length=264)),
                ('chart_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnumonitor.Chart')),
            ],
        ),
    ]
