# Generated by Django 2.1.5 on 2019-05-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0009_data_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_error',
            old_name='error',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='data_error',
            name='chart_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gnumonitor.Chart'),
        ),
    ]
