# Generated by Django 2.2.1 on 2019-05-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0010_auto_20190501_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('ip', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Host_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('description', models.CharField(max_length=264)),
                ('etype', models.CharField(max_length=264)),
                ('host_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnumonitor.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Host_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('cpu', models.FloatField()),
                ('ram', models.FloatField()),
                ('host_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnumonitor.Host')),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='host_object',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gnumonitor.Host'),
            preserve_default=False,
        ),
    ]
