# Generated by Django 2.2.1 on 2019-05-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0011_auto_20190522_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_data',
            old_name='cpu',
            new_name='cpu_percent',
        ),
        migrations.RenameField(
            model_name='host_data',
            old_name='time',
            new_name='host_time',
        ),
        migrations.RenameField(
            model_name='host_data',
            old_name='ram',
            new_name='memory_percent',
        ),
        migrations.AddField(
            model_name='host_data',
            name='disk_percent',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chart',
            name='host_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gnumonitor.Host'),
        ),
    ]
