# Generated by Django 2.2.1 on 2019-05-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0012_auto_20190523_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('description', models.CharField(max_length=264)),
                ('etype', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Sys_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('description', models.CharField(max_length=264)),
                ('etype', models.CharField(max_length=264)),
            ],
        ),
        migrations.RenameModel(
            old_name='Data_Chart',
            new_name='Chart_Data',
        ),
        migrations.RenameModel(
            old_name='Host_Error',
            new_name='Host_Report',
        ),
        migrations.RenameField(
            model_name='host_data',
            old_name='host_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='chart',
            name='host_object',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gnumonitor.Host'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Data_Error',
        ),
        migrations.AddField(
            model_name='chart_report',
            name='chart_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnumonitor.Chart'),
        ),
    ]
