# Generated by Django 2.1.5 on 2019-02-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnumonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('throughput', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Topic2',
        ),
    ]
